name: Build Hello World executable
on: [push]
jobs:
  run:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: '4.08.1'
    - run: opam exec -- dune build
    - run: opam install -t . --deps-only
    - run: opam exec -- dune runtest
